#pragma once
#define _USE_MATH_DEFINES

#include <Windows.h>
#include <stdlib.h>
#include <vector>
#include <thread>
#include <array>
#include <list>
#include <string>
#include <atlimage.h>
#include <iostream>
#include <random>
#include <unordered_map>
#include "../ShootingGameProject/resource.h"
#include "../Include/json/json.h"
#include "KeyState.h"
#include "Vec.h"
#include "Definition.h"
#include "CreateOption.h"
#include "FireOption.h"
#include "Utils.h"
